name: Lint and Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cppcheck clang-format

      - name: Build (native amd64)
        run: make -C src

      - name: Run cppcheck
        run: cppcheck --enable=all --error-exitcode=1 --std=c11 --suppress=missingIncludeSystem src

      - name: Check formatting
        run: clang-format --dry-run --Werror $(find src -name '*.c' -o -name '*.h')
