name: "Cross Compile and Publish Binary"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  build-armhf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Build for Raspberry Pi (armhf)
        run: |
          make -C src CC=arm-linux-gnueabihf-gcc
          mv src/accelerometer accelerometer

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: accelerometer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
